name: 'Opentofu with OIDC'

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - 'IAC/DEV/**'    # Only trigger if files in DEV change
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}

jobs:
  opentofu-dev:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo # pulls the repo code
        uses: actions/checkout@v4
      
      - name: Install OpenTofu CLI
        run: |
          curl -LO https://github.com/opentofu/opentofu/releases/download/v1.10.6/tofu_1.10.6_linux_amd64.zip
          unzip -j tofu_1.10.6_linux_amd64.zip tofu  # -j extracts just the file without directories
          sudo mv tofu /usr/local/bin/
          tofu version


      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: false  # optional, no PowerShell session needed

      - name: Initialize OpenTofu
        working-directory: IAC/DEV
        run: tofu init -backend-config=backend.dev.tfvars

      - name: Plan OpenTofu
        working-directory: IAC/DEV
        run: |
          tofu plan -out=tfplan
        # Save the plan as an artifact so apply job can use it

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: IAC/DEV/tfplan
  
  opentofu-apply:
    name: Apply OpenTofu
    runs-on: ubuntu-latest
    needs: opentofu-dev  # will only run if plan job succeeds
    environment: dev  # manual approval
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Install OpenTofu CLI
        run: |
          curl -LO https://github.com/opentofu/opentofu/releases/download/v1.10.6/tofu_1.10.6_linux_amd64.zip
          unzip -j tofu_1.10.6_linux_amd64.zip tofu
          sudo mv tofu /usr/local/bin/
          tofu version

      - name: Login to Azure with OIDC
        uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}
          enable-AzPSSession: false

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: IAC/DEV

      - name: Apply OpenTofu
        working-directory: IAC/DEV
        run: tofu apply -auto-approve tfplan
