name: 'Opentofu with OIDC'

on:
  push:
    branches: [ "main" ]
    #paths:
    #  - 'IAC/DEV/**'    # Only trigger if files in DEV change
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read

env:
  ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
  OPENTOFU_VERSION: 1.10.6

jobs:
  # First job (opentofu-dev) ---------------------------------------------
  # 1. Checkout repo -> pull the current repo
  # 2. Cache OpenTofu providers
  # 3. Install OpenTofu CLI (coming from composite action opentofu-setup)
  # 4. Login to Azure with OIDC (coming from composite action opentofu-setup)
  # 5. Initialize OpenTofu
  # 6. Plan OpenTofu
  # 7. Upload the plan as an artifact

  # Second job (opentofu-apply) -------------------------------------------
  # 1. Checkout repo -> pull the current repo
  # 2. Cache OpenTofu providers
  # 3. Install OpenTofu CLI (coming from composite action opentofu-setup)
  # 4. Login to Azure with OIDC (coming from composite action opentofu-setup)
  # 5. Download the plan artifact
  # 6. Apply OpenTofu
  # -------------------------------------------
  opentofu-dev-setup:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    env:
      ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ vars.ARM_TENANT_ID }}
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Repo # pulls the repo code
        uses: actions/checkout@v4
      
      - name: Setup OpenTofu + Azure
        uses: ./.github/actions/opentofu-setup
        with:
          opentofu_version: ${{ env.OPENTOFU_VERSION }}
          azure_client_id: ${{ env.ARM_CLIENT_ID }}
          azure_tenant_id: ${{ env.ARM_TENANT_ID }}
          azure_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Initialize OpenTofu
        working-directory: IAC/DEV
        run: tofu init -backend-config=backend.dev.tfvars

      - name: Format OpenTofu code
        working-directory: IAC/DEV
        run: tofu fmt -recursive

      - name: Validate OpenTofu code
        working-directory: IAC/DEV
        run: tofu validate

      - name: Plan OpenTofu
        working-directory: IAC/DEV
        run: |
          tofu plan -out=tfplan -input=false
        # Save the plan as an artifact so apply job can use it

      # Upload providers, lock file, and plan as artifacts
      - name: Upload OpenTofu artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tofu-artifacts
          path: |
            IAC/DEV/.terraform.lock.hcl
            IAC/DEV/tfplan
  
  opentofu-dev-apply:
    name: Apply OpenTofu
    runs-on: ubuntu-latest
    needs: opentofu-dev-setup  # will only run if plan job succeeds
    environment: dev  # manual approval
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup OpenTofu + Azure
        uses: ./.github/actions/opentofu-setup
        with:
          opentofu_version: ${{ env.OPENTOFU_VERSION }}
          azure_client_id: ${{ env.ARM_CLIENT_ID }}
          azure_tenant_id: ${{ env.ARM_TENANT_ID }}
          azure_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tofu-artifacts
          path: IAC/DEV

      # Restore provider cache
      - name: Restore OpenTofu provider cache
        uses: actions/cache@v4
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-opentofu-${{ hashFiles('IAC/DEV/.terraform.lock.hcl') }}

      # Initialize OpenTofu in the apply job
      - name: Initialize OpenTofu
        working-directory: IAC/DEV
        run: tofu init -backend-config=backend.dev.tfvars

      - name: Apply OpenTofu
        working-directory: IAC/DEV
        run: tofu apply -auto-approve tfplan
